name 'simpleDeploy'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures simpleDeploy'
long_description 'Installs/Configures simpleDeploy'
version '0.1.0'
